### ISSUE TITLE
数据集版本问题

### ISSUE THREAD

**Issue by ZoangX** [DYZhang09/SAM3D#2]
请问，您的项目用的是waymo哪个版本的数据集？官网现在有好多个版本（如下图）
![image](https://github.com/DYZhang09/SAM3D/assets/58078383/d2d0f0ff-5c5e-4006-9129-e475e76b97fd)

还有个问题：
        您的项目是只用到了验证集吗？测试集和训练集都没有用到对吧？

**Comment by DYZhang09** [comment]
我们使用的是 v1.2，并且只用到了验证集

We use the waymo open dataset v1.2 and only use the validation set

**Comment by ZoangX** [comment]
好的，感谢回复，我会尽快尝试这个有趣的项目！
