### ISSUE TITLE
代码调试问题

### ISSUE THREAD

**Issue by ZoangX** [DYZhang09/SAM3D#3]
当我在终端运行：python tools/test.py projects/configs/sam3d_intensity_bev_waymo_car.py fake.pth 
可以成功运行；

但是当我在pycharm中调试时，当代码调试到第121行时，
遇到如下错误：FileNotFoundError: class `SAMDet3D` in projects/core/sam_det3d.py: class `MaskAutoGenerator` in projects/core/mask_utils.py: [Errno 2] No such file or directory: 'projects/pretrain_weights/sam_vit_h_4b8939.pth'

针对FlieNotFoundError，实际上类SAMDet3D和MaskAutoGenerator就在上述路径脚本文件里，为什么会报**文件没有发现**这个错误呢？

**Comment by DYZhang09** [comment]
We use the pre-trained SAM in our project, so go to [segment-anything model checkpoints](https://github.com/facebookresearch/segment-anything#model-checkpoints) to download weights and put them into `projects/pretrain_weights`

我们要用到 SAM 的预训练权重，需要把 SAM 的预训练权重下载下来并放到 `projects/pretrain_weights` 里面，这里报错是没有找到 SAM 的权重文件

**Comment by ZoangX** [comment]
> We use the pre-trained SAM in our project, so go to [segment-anything model checkpoints](https://github.com/facebookresearch/segment-anything#model-checkpoints) to download weights and put them into `projects/pretrain_weights`
> 
> 我们要用到 SAM 的预训练权重，需要把 SAM 的预训练权重下载下来并放到 `projects/pretrain_weights` 里面，这里报错是没有找到 SAM 的权重文件

nonono，您可能理解错了，我把SAM预训练权重已经放到对应文件夹下，我用了waymo中的一个*.tfrecord做预测，我可以在终端成功推理并生成可视化鸟瞰图结果，但是，我在Pycharm中运行`test.py`就报错了，您仔细看一下错误，您只回答了我的error2，并没有回答error1，请指教error1！

**Comment by DYZhang09** [comment]
我这里看到的 Error 信息就是在说找不到权重文件，我推测是不是 Pycharm 中运行的时候工作路径没在项目根目录

**Comment by ZoangX** [comment]
蟹蟹，已解决！
