### ISSUE TITLE
demo.py

### ISSUE THREAD

**Issue by ZoangX** [DYZhang09/SAM3D#4]
请问，有没有单帧点云的demo.py的推理文件呢？

**Comment by DYZhang09** [comment]
我们推理时本身就是使用的单帧

**Comment by ZoangX** [comment]
我意思是有没有像mmdet3d官方提供的[demo](https://www.bilibili.com/video/BV1E44y1Q7qi/?spm_id_from=333.788&vd_source=be3b0ea866bc855aca0dab445df7314d)那样，我只输入一帧数据，最终直接显示可视化结果。不需要像您的项目中test.py那样，还得评估精度什么的

**Comment by DYZhang09** [comment]
我们没有实现这个，不过你可以参照官方的那样去实现一个

**Comment by ZoangX** [comment]
好，有时间我会尝试下，但可能需要先读懂代码，方便留个联系方式吗，我是南师的在读硕士，后续想能跟您多聊聊！

**Comment by DYZhang09** [comment]
我的首页留有QQ
